insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Ivanov', 'Peter', 'Sergeevich', 'Enrolled', 'Moscow')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Petrov', 'Aleksey', 'Igorevich', 'Not enrolled', 'Saint-Petersburg')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Sidorova', 'Maria', 'Andreevna', 'Enrolled', 'Kazan')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Kuznetsov', 'Dmitry', 'Pavlovich', 'Enrolled', 'Novosibirsk')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Volkova', 'Anna', 'Viktorovna', 'Not enrolled', 'Yekaterinburg')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Morozov', 'Ivan', 'Vladimirovich', 'Enrolled', 'Nizhny Novgorod')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Smirnova', 'Elena', 'Alekseevna', 'Not enrolled', 'Rostov-on-Don')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Fedorov', 'Maksim', 'Sergeevich', 'Enrolled', 'Samara')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Alekseeva', 'Olga', 'Igorevna', 'Not enrolled', 'Perm')
insert into Applicants (Applicant_surname, Applicant_name, Applicant_patronymic, Applicant_status, Applicant_city) values ('Grigoriev', 'Nikita', 'Andreevich', 'Enrolled', 'Krasnodar')

insert into Specialties (Specialty_name, Specialty_vacancies) values ('Software Engineering', 25)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Information Systems', 20)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Cybersecurity', 15)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Applied Mathematics', 18)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Economics', 30)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Management', 22)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Marketing', 20)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Philology', 12)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('History', 10)
insert into Specialties (Specialty_name, Specialty_vacancies) values ('Journalism', 16)

insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (1, 1, 'Enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (2, 1, 'Enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (3, 2, 'Not enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (4, 3, 'Not enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (5, 4, 'Not enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (6, 5, 'Not enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (7, 6, 'Collected documents')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (8, 7, 'Collected documents')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (9, 8, 'Enrolled')
insert into Statements (Statement_applicant_code, Statement_specialty_code, Statement_status) values (10, 9, 'Enrolled')

insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (1, 1, '2024-06-10', 60)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (2, 2, '2024-06-15', 55)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (3, 3, '2024-06-18', 50)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (4, 1, '2024-06-20', 60)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (5, 7, '2024-06-22', 55)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (6, 8, '2024-06-25', 50)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (7, 9, '2024-06-27', 60)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (8, 5, '2024-06-29', 55)
insert into Exams (Exam_specialty_code, Exam_discipline_code, Exam_date, Exam_positive_score) values (9, 4, '2024-07-01', 50)

insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (1, 1, 85)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (2, 1, 45)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (3, 3, 67)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (4, 4, 70)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (5, 5, 50)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (6, 6, 80)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (7, 7, 55)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (8, 8, 88)
insert into Assessments (Assessment_applicant_code, Assessment_exam_code, Assessment_assessment) values (9, 9, 45)